apiVersion: apps/v1
kind: Deployment
metadata:
  name: funny-app
spec:
  replicas: {{int .Values.replicas}}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: funny-app
  template:
    metadata:
      labels:
        app: funny-app
    spec:
      containers:
      - image: {{.Values.image}}
        name: python-funny-app
        ports:
        - containerPort: 5000